namespace PkFactory.Constants;

public enum FrontierMon
{
    Sunkern = 0,
    Azurill = 1,
    Caterpie = 2,
    Weedle = 3,
    Wurmple = 4,
    Ralts = 5,
    Magikarp = 6,
    Feebas = 7,
    Metapod = 8,
    Kakuna = 9,
    Pichu = 10,
    Silcoon = 11,
    Cascoon = 12,
    Igglybuff = 13,
    Wooper = 14,
    Tyrogue = 15,
    Sentret = 16,
    Cleffa = 17,
    Seedot = 18,
    Lotad = 19,
    Poochyena = 20,
    Shedinja = 21,
    Makuhita = 22,
    Whismur = 23,
    Zigzagoon = 24,
    Zubat = 25,
    Togepi = 26,
    Spinarak = 27,
    Marill = 28,
    Hoppip = 29,
    Slugma = 30,
    Swinub = 31,
    Smeargle = 32,
    Pidgey = 33,
    Rattata = 34,
    Wynaut = 35,
    Skitty = 36,
    Spearow = 37,
    Hoothoot = 38,
    Diglett = 39,
    Ledyba = 40,
    Nincada = 41,
    Surskit = 42,
    Jigglypuff = 43,
    Taillow = 44,
    Wingull = 45,
    NidoranM = 46,
    NidoranF = 47,
    Kirlia = 48,
    Mareep = 49,
    Meditite = 50,
    Slakoth = 51,
    Paras = 52,
    Ekans = 53,
    Ditto = 54,
    Barboach = 55,
    Meowth = 56,
    Pineco = 57,
    Trapinch = 58,
    Spheal = 59,
    Horsea = 60,
    Shroomish = 61,
    Shuppet = 62,
    Duskull = 63,
    Electrike = 64,
    Vulpix = 65,
    Pikachu = 66,
    Sandshrew = 67,
    Poliwag = 68,
    Bellsprout = 69,
    Geodude = 70,
    Dratini = 71,
    Snubbull = 72,
    Remoraid = 73,
    Larvitar = 74,
    Baltoy = 75,
    Snorunt = 76,
    Bagon = 77,
    Beldum = 78,
    Gulpin = 79,
    Venonat = 80,
    Mankey = 81,
    Machop = 82,
    Shellder = 83,
    Smoochum = 84,
    Numel = 85,
    Carvanha = 86,
    Corphish = 87,
    Charmander = 88,
    Cyndaquil = 89,
    Abra = 90,
    Doduo = 91,
    Gastly = 92,
    Swablu = 93,
    Treecko = 94,
    Torchic = 95,
    Mudkip = 96,
    Squirtle = 97,
    Totodile = 98,
    Slowpoke = 99,
    Bulbasaur = 100,
    Chikorita = 101,
    Oddish = 102,
    Psyduck = 103,
    Cubone = 104,
    Goldeen = 105,
    Natu = 106,
    Clefairy = 107,
    Magnemite = 108,
    Seel = 109,
    Grimer = 110,
    Krabby = 111,
    Exeggcute = 112,
    Eevee = 113,
    Drowzee = 114,
    Voltorb = 115,
    Chinchou = 116,
    Teddiursa = 117,
    Delibird = 118,
    Houndour = 119,
    Phanpy = 120,
    Spoink = 121,
    Aron = 122,
    Luvdisc = 123,
    Tentacool = 124,
    Cacnea = 125,
    Unown = 126,
    Koffing = 127,
    Staryu = 128,
    Skiploom = 129,
    Nuzleaf = 130,
    Lombre = 131,
    Vibrava = 132,
    Rhyhorn = 133,
    Clamperl = 134,
    Pidgeotto = 135,
    Growlithe = 136,
    Farfetchd = 137,
    Omanyte = 138,
    Kabuto = 139,
    Lileep = 140,
    Anorith = 141,
    Aipom = 142,
    Elekid = 143,
    Loudred = 144,
    Spinda = 145,
    Nidorina = 146,
    Nidorino = 147,
    Flaaffy = 148,
    Magby = 149,
    Nosepass = 150,
    Corsola = 151,
    Mawile = 152,
    Butterfree = 153,
    Beedrill = 154,
    Poliwhirl = 155,
    Onix = 156,
    Beautifly = 157,
    Dustox = 158,
    Ledian = 159,
    Ariados = 160,
    Yanma = 161,
    Delcatty1 = 162,
    Sableye1 = 163,
    Lickitung1 = 164,
    Weepinbell1 = 165,
    Graveler1 = 166,
    Gloom1 = 167,
    Porygon1 = 168,
    Kadabra1 = 169,
    Wailmer1 = 170,
    Roselia1 = 171,
    Volbeat1 = 172,
    Illumise1 = 173,
    Ivysaur1 = 174,
    Charmeleon1 = 175,
    Wartortle1 = 176,
    Parasect1 = 177,
    Machoke1 = 178,
    Haunter1 = 179,
    Bayleef1 = 180,
    Quilava1 = 181,
    Croconaw1 = 182,
    Togetic1 = 183,
    Murkrow1 = 184,
    Wobbuffet1 = 185,
    Plusle1 = 186,
    Minun1 = 187,
    Grovyle1 = 188,
    Combusken1 = 189,
    Marshtomp1 = 190,
    Ponyta1 = 191,
    Azumarill1 = 192,
    Sudowoodo1 = 193,
    Magcargo1 = 194,
    Pupitar1 = 195,
    Sealeo1 = 196,
    Raticate1 = 197,
    Masquerain1 = 198,
    Furret1 = 199,
    Dunsparce1 = 200,
    Dragonair1 = 201,
    Mightyena1 = 202,
    Linoone1 = 203,
    Castform1 = 204,
    Shelgon1 = 205,
    Metang1 = 206,
    Wigglytuff1 = 207,
    Sunflora1 = 208,
    Chimecho1 = 209,
    Gligar1 = 210,
    Qwilfish1 = 211,
    Sneasel1 = 212,
    Pelipper1 = 213,
    Swellow1 = 214,
    Lairon1 = 215,
    Tangela1 = 216,
    Arbok1 = 217,
    Persian1 = 218,
    Seadra1 = 219,
    Kecleon1 = 220,
    Vigoroth1 = 221,
    Lunatone1 = 222,
    Solrock1 = 223,
    Noctowl1 = 224,
    Sandslash1 = 225,
    Venomoth1 = 226,
    Chansey1 = 227,
    Seaking1 = 228,
    Jumpluff1 = 229,
    Piloswine1 = 230,
    Golbat1 = 231,
    Primeape1 = 232,
    Hitmonlee1 = 233,
    Hitmonchan1 = 234,
    Girafarig1 = 235,
    Hitmontop1 = 236,
    Banette1 = 237,
    Ninjask1 = 238,
    Seviper1 = 239,
    Zangoose1 = 240,
    Camerupt1 = 241,
    Sharpedo1 = 242,
    Tropius1 = 243,
    Magneton1 = 244,
    Mantine1 = 245,
    Stantler1 = 246,
    Absol1 = 247,
    Swalot1 = 248,
    Crawdaunt1 = 249,
    Pidgeot1 = 250,
    Grumpig1 = 251,
    Torkoal1 = 252,
    Kingler1 = 253,
    Cacturne1 = 254,
    Bellossom1 = 255,
    Octillery1 = 256,
    Huntail1 = 257,
    Gorebyss1 = 258,
    Relicanth1 = 259,
    Omastar1 = 260,
    Kabutops1 = 261,
    Poliwrath1 = 262,
    Scyther1 = 263,
    Pinsir1 = 264,
    Politoed1 = 265,
    Cloyster1 = 266,
    Delcatty2 = 267,
    Sableye2 = 268,
    Lickitung2 = 269,
    Weepinbell2 = 270,
    Graveler2 = 271,
    Gloom2 = 272,
    Porygon2 = 273,
    Kadabra2 = 274,
    Wailmer2 = 275,
    Roselia2 = 276,
    Volbeat2 = 277,
    Illumise2 = 278,
    Ivysaur2 = 279,
    Charmeleon2 = 280,
    Wartortle2 = 281,
    Parasect2 = 282,
    Machoke2 = 283,
    Haunter2 = 284,
    Bayleef2 = 285,
    Quilava2 = 286,
    Croconaw2 = 287,
    Togetic2 = 288,
    Murkrow2 = 289,
    Wobbuffet2 = 290,
    Plusle2 = 291,
    Minun2 = 292,
    Grovyle2 = 293,
    Combusken2 = 294,
    Marshtomp2 = 295,
    Ponyta2 = 296,
    Azumarill2 = 297,
    Sudowoodo2 = 298,
    Magcargo2 = 299,
    Pupitar2 = 300,
    Sealeo2 = 301,
    Raticate2 = 302,
    Masquerain2 = 303,
    Furret2 = 304,
    Dunsparce2 = 305,
    Dragonair2 = 306,
    Mightyena2 = 307,
    Linoone2 = 308,
    Castform2 = 309,
    Shelgon2 = 310,
    Metang2 = 311,
    Wigglytuff2 = 312,
    Sunflora2 = 313,
    Chimecho2 = 314,
    Gligar2 = 315,
    Qwilfish2 = 316,
    Sneasel2 = 317,
    Pelipper2 = 318,
    Swellow2 = 319,
    Lairon2 = 320,
    Tangela2 = 321,
    Arbok2 = 322,
    Persian2 = 323,
    Seadra2 = 324,
    Kecleon2 = 325,
    Vigoroth2 = 326,
    Lunatone2 = 327,
    Solrock2 = 328,
    Noctowl2 = 329,
    Sandslash2 = 330,
    Venomoth2 = 331,
    Chansey2 = 332,
    Seaking2 = 333,
    Jumpluff2 = 334,
    Piloswine2 = 335,
    Golbat2 = 336,
    Primeape2 = 337,
    Hitmonlee2 = 338,
    Hitmonchan2 = 339,
    Girafarig2 = 340,
    Hitmontop2 = 341,
    Banette2 = 342,
    Ninjask2 = 343,
    Seviper2 = 344,
    Zangoose2 = 345,
    Camerupt2 = 346,
    Sharpedo2 = 347,
    Tropius2 = 348,
    Magneton2 = 349,
    Mantine2 = 350,
    Stantler2 = 351,
    Absol2 = 352,
    Swalot2 = 353,
    Crawdaunt2 = 354,
    Pidgeot2 = 355,
    Grumpig2 = 356,
    Torkoal2 = 357,
    Kingler2 = 358,
    Cacturne2 = 359,
    Bellossom2 = 360,
    Octillery2 = 361,
    Huntail2 = 362,
    Gorebyss2 = 363,
    Relicanth2 = 364,
    Omastar2 = 365,
    Kabutops2 = 366,
    Poliwrath2 = 367,
    Scyther2 = 368,
    Pinsir2 = 369,
    Politoed2 = 370,
    Cloyster2 = 371,
    Dugtrio1 = 372,
    Medicham1 = 373,
    Misdreavus1 = 374,
    Fearow1 = 375,
    Granbull1 = 376,
    Jynx1 = 377,
    Dusclops1 = 378,
    Dodrio1 = 379,
    MrMime1 = 380,
    Lanturn1 = 381,
    Breloom1 = 382,
    Forretress1 = 383,
    Whiscash1 = 384,
    Xatu1 = 385,
    Skarmory1 = 386,
    Marowak1 = 387,
    Quagsire1 = 388,
    Clefable1 = 389,
    Hariyama1 = 390,
    Raichu1 = 391,
    Dewgong1 = 392,
    Manectric1 = 393,
    Vileplume1 = 394,
    Victreebel1 = 395,
    Electrode1 = 396,
    Exploud1 = 397,
    Shiftry1 = 398,
    Glalie1 = 399,
    Ludicolo1 = 400,
    Hypno1 = 401,
    Golem1 = 402,
    Rhydon1 = 403,
    Alakazam1 = 404,
    Weezing1 = 405,
    Kangaskhan1 = 406,
    Electabuzz1 = 407,
    Tauros1 = 408,
    Slowbro1 = 409,
    Slowking1 = 410,
    Miltank1 = 411,
    Altaria1 = 412,
    Nidoqueen1 = 413,
    Nidoking1 = 414,
    Magmar1 = 415,
    Cradily1 = 416,
    Armaldo1 = 417,
    Golduck1 = 418,
    Rapidash1 = 419,
    Muk1 = 420,
    Gengar1 = 421,
    Ampharos1 = 422,
    Scizor1 = 423,
    Heracross1 = 424,
    Ursaring1 = 425,
    Houndoom1 = 426,
    Donphan1 = 427,
    Claydol1 = 428,
    Wailord1 = 429,
    Ninetales1 = 430,
    Machamp1 = 431,
    Shuckle1 = 432,
    Steelix1 = 433,
    Tentacruel1 = 434,
    Aerodactyl1 = 435,
    Porygon21 = 436,
    Gardevoir1 = 437,
    Exeggutor1 = 438,
    Starmie1 = 439,
    Flygon1 = 440,
    Venusaur1 = 441,
    Vaporeon1 = 442,
    Jolteon1 = 443,
    Flareon1 = 444,
    Meganium1 = 445,
    Espeon1 = 446,
    Umbreon1 = 447,
    Blastoise1 = 448,
    Feraligatr1 = 449,
    Aggron1 = 450,
    Blaziken1 = 451,
    Walrein1 = 452,
    Sceptile1 = 453,
    Charizard1 = 454,
    Typhlosion1 = 455,
    Lapras1 = 456,
    Crobat1 = 457,
    Swampert1 = 458,
    Gyarados1 = 459,
    Snorlax1 = 460,
    Kingdra1 = 461,
    Blissey1 = 462,
    Milotic1 = 463,
    Arcanine1 = 464,
    Salamence1 = 465,
    Metagross1 = 466,
    Slaking1 = 467,
    Dugtrio2 = 468,
    Medicham2 = 469,
    Marowak2 = 470,
    Quagsire2 = 471,
    Misdreavus2 = 472,
    Fearow2 = 473,
    Granbull2 = 474,
    Jynx2 = 475,
    Dusclops2 = 476,
    Dodrio2 = 477,
    MrMime2 = 478,
    Lanturn2 = 479,
    Breloom2 = 480,
    Forretress2 = 481,
    Skarmory2 = 482,
    Whiscash2 = 483,
    Xatu2 = 484,
    Clefable2 = 485,
    Hariyama2 = 486,
    Raichu2 = 487,
    Dewgong2 = 488,
    Manectric2 = 489,
    Vileplume2 = 490,
    Victreebel2 = 491,
    Electrode2 = 492,
    Exploud2 = 493,
    Shiftry2 = 494,
    Glalie2 = 495,
    Ludicolo2 = 496,
    Hypno2 = 497,
    Golem2 = 498,
    Rhydon2 = 499,
    Alakazam2 = 500,
    Weezing2 = 501,
    Kangaskhan2 = 502,
    Electabuzz2 = 503,
    Tauros2 = 504,
    Slowbro2 = 505,
    Slowking2 = 506,
    Miltank2 = 507,
    Altaria2 = 508,
    Nidoqueen2 = 509,
    Nidoking2 = 510,
    Magmar2 = 511,
    Cradily2 = 512,
    Armaldo2 = 513,
    Golduck2 = 514,
    Rapidash2 = 515,
    Muk2 = 516,
    Gengar2 = 517,
    Ampharos2 = 518,
    Scizor2 = 519,
    Heracross2 = 520,
    Ursaring2 = 521,
    Houndoom2 = 522,
    Donphan2 = 523,
    Claydol2 = 524,
    Wailord2 = 525,
    Ninetales2 = 526,
    Machamp2 = 527,
    Shuckle2 = 528,
    Steelix2 = 529,
    Tentacruel2 = 530,
    Aerodactyl2 = 531,
    Porygon22 = 532,
    Gardevoir2 = 533,
    Exeggutor2 = 534,
    Starmie2 = 535,
    Flygon2 = 536,
    Venusaur2 = 537,
    Vaporeon2 = 538,
    Jolteon2 = 539,
    Flareon2 = 540,
    Meganium2 = 541,
    Espeon2 = 542,
    Umbreon2 = 543,
    Blastoise2 = 544,
    Feraligatr2 = 545,
    Aggron2 = 546,
    Blaziken2 = 547,
    Walrein2 = 548,
    Sceptile2 = 549,
    Charizard2 = 550,
    Typhlosion2 = 551,
    Lapras2 = 552,
    Crobat2 = 553,
    Swampert2 = 554,
    Gyarados2 = 555,
    Snorlax2 = 556,
    Kingdra2 = 557,
    Blissey2 = 558,
    Milotic2 = 559,
    Arcanine2 = 560,
    Salamence2 = 561,
    Metagross2 = 562,
    Slaking2 = 563,
    Dugtrio3 = 564,
    Medicham3 = 565,
    Misdreavus3 = 566,
    Fearow3 = 567,
    Granbull3 = 568,
    Jynx3 = 569,
    Dusclops3 = 570,
    Dodrio3 = 571,
    MrMime3 = 572,
    Lanturn3 = 573,
    Breloom3 = 574,
    Forretress3 = 575,
    Whiscash3 = 576,
    Xatu3 = 577,
    Skarmory3 = 578,
    Marowak3 = 579,
    Quagsire3 = 580,
    Clefable3 = 581,
    Hariyama3 = 582,
    Raichu3 = 583,
    Dewgong3 = 584,
    Manectric3 = 585,
    Vileplume3 = 586,
    Victreebel3 = 587,
    Electrode3 = 588,
    Exploud3 = 589,
    Shiftry3 = 590,
    Glalie3 = 591,
    Ludicolo3 = 592,
    Hypno3 = 593,
    Golem3 = 594,
    Rhydon3 = 595,
    Alakazam3 = 596,
    Weezing3 = 597,
    Kangaskhan3 = 598,
    Electabuzz3 = 599,
    Tauros3 = 600,
    Slowbro3 = 601,
    Slowking3 = 602,
    Miltank3 = 603,
    Altaria3 = 604,
    Nidoqueen3 = 605,
    Nidoking3 = 606,
    Magmar3 = 607,
    Cradily3 = 608,
    Armaldo3 = 609,
    Golduck3 = 610,
    Rapidash3 = 611,
    Muk3 = 612,
    Gengar3 = 613,
    Ampharos3 = 614,
    Scizor3 = 615,
    Heracross3 = 616,
    Ursaring3 = 617,
    Houndoom3 = 618,
    Donphan3 = 619,
    Claydol3 = 620,
    Wailord3 = 621,
    Ninetales3 = 622,
    Machamp3 = 623,
    Shuckle3 = 624,
    Steelix3 = 625,
    Tentacruel3 = 626,
    Aerodactyl3 = 627,
    Porygon23 = 628,
    Gardevoir3 = 629,
    Exeggutor3 = 630,
    Starmie3 = 631,
    Flygon3 = 632,
    Venusaur3 = 633,
    Vaporeon3 = 634,
    Jolteon3 = 635,
    Flareon3 = 636,
    Meganium3 = 637,
    Espeon3 = 638,
    Umbreon3 = 639,
    Blastoise3 = 640,
    Feraligatr3 = 641,
    Aggron3 = 642,
    Blaziken3 = 643,
    Walrein3 = 644,
    Sceptile3 = 645,
    Charizard3 = 646,
    Typhlosion3 = 647,
    Lapras3 = 648,
    Crobat3 = 649,
    Swampert3 = 650,
    Gyarados3 = 651,
    Snorlax3 = 652,
    Kingdra3 = 653,
    Blissey3 = 654,
    Milotic3 = 655,
    Arcanine3 = 656,
    Salamence3 = 657,
    Metagross3 = 658,
    Slaking3 = 659,
    Dugtrio4 = 660,
    Medicham4 = 661,
    Misdreavus4 = 662,
    Fearow4 = 663,
    Granbull4 = 664,
    Jynx4 = 665,
    Dusclops4 = 666,
    Dodrio4 = 667,
    MrMime4 = 668,
    Lanturn4 = 669,
    Breloom4 = 670,
    Forretress4 = 671,
    Whiscash4 = 672,
    Xatu4 = 673,
    Skarmory4 = 674,
    Marowak4 = 675,
    Quagsire4 = 676,
    Clefable4 = 677,
    Hariyama4 = 678,
    Raichu4 = 679,
    Dewgong4 = 680,
    Manectric4 = 681,
    Vileplume4 = 682,
    Victreebel4 = 683,
    Electrode4 = 684,
    Exploud4 = 685,
    Shiftry4 = 686,
    Glalie4 = 687,
    Ludicolo4 = 688,
    Hypno4 = 689,
    Golem4 = 690,
    Rhydon4 = 691,
    Alakazam4 = 692,
    Weezing4 = 693,
    Kangaskhan4 = 694,
    Electabuzz4 = 695,
    Tauros4 = 696,
    Slowbro4 = 697,
    Slowking4 = 698,
    Miltank4 = 699,
    Altaria4 = 700,
    Nidoqueen4 = 701,
    Nidoking4 = 702,
    Magmar4 = 703,
    Cradily4 = 704,
    Armaldo4 = 705,
    Golduck4 = 706,
    Rapidash4 = 707,
    Muk4 = 708,
    Gengar4 = 709,
    Ampharos4 = 710,
    Scizor4 = 711,
    Heracross4 = 712,
    Ursaring4 = 713,
    Houndoom4 = 714,
    Donphan4 = 715,
    Claydol4 = 716,
    Wailord4 = 717,
    Ninetales4 = 718,
    Machamp4 = 719,
    Shuckle4 = 720,
    Steelix4 = 721,
    Tentacruel4 = 722,
    Aerodactyl4 = 723,
    Porygon24 = 724,
    Gardevoir4 = 725,
    Exeggutor4 = 726,
    Starmie4 = 727,
    Flygon4 = 728,
    Venusaur4 = 729,
    Vaporeon4 = 730,
    Jolteon4 = 731,
    Flareon4 = 732,
    Meganium4 = 733,
    Espeon4 = 734,
    Umbreon4 = 735,
    Blastoise4 = 736,
    Feraligatr4 = 737,
    Aggron4 = 738,
    Blaziken4 = 739,
    Walrein4 = 740,
    Sceptile4 = 741,
    Charizard4 = 742,
    Typhlosion4 = 743,
    Lapras4 = 744,
    Crobat4 = 745,
    Swampert4 = 746,
    Gyarados4 = 747,
    Snorlax4 = 748,
    Kingdra4 = 749,
    Blissey4 = 750,
    Milotic4 = 751,
    Arcanine4 = 752,
    Salamence4 = 753,
    Metagross4 = 754,
    Slaking4 = 755,
    Articuno1 = 756,
    Zapdos1 = 757,
    Moltres1 = 758,
    Raikou1 = 759,
    Entei1 = 760,
    Suicune1 = 761,
    Regirock1 = 762,
    Regice1 = 763,
    Registeel1 = 764,
    Latias1 = 765,
    Latios1 = 766,
    Articuno2 = 767,
    Zapdos2 = 768,
    Moltres2 = 769,
    Raikou2 = 770,
    Entei2 = 771,
    Suicune2 = 772,
    Regirock2 = 773,
    Regice2 = 774,
    Registeel2 = 775,
    Latias2 = 776,
    Latios2 = 777,
    Articuno3 = 778,
    Zapdos3 = 779,
    Moltres3 = 780,
    Raikou3 = 781,
    Entei3 = 782,
    Suicune3 = 783,
    Regirock3 = 784,
    Regice3 = 785,
    Registeel3 = 786,
    Latias3 = 787,
    Latios3 = 788,
    Articuno4 = 789,
    Zapdos4 = 790,
    Moltres4 = 791,
    Raikou4 = 792,
    Entei4 = 793,
    Suicune4 = 794,
    Regirock4 = 795,
    Regice4 = 796,
    Registeel4 = 797,
    Latias4 = 798,
    Latios4 = 799,
    Gengar5 = 800,
    Gengar6 = 801,
    Gengar7 = 802,
    Gengar8 = 803,
    Ursaring5 = 804,
    Ursaring6 = 805,
    Ursaring7 = 806,
    Ursaring8 = 807,
    Machamp5 = 808,
    Machamp6 = 809,
    Machamp7 = 810,
    Machamp8 = 811,
    Gardevoir5 = 812,
    Gardevoir6 = 813,
    Gardevoir7 = 814,
    Gardevoir8 = 815,
    Starmie5 = 816,
    Starmie6 = 817,
    Starmie7 = 818,
    Starmie8 = 819,
    Lapras5 = 820,
    Lapras6 = 821,
    Lapras7 = 822,
    Lapras8 = 823,
    Snorlax5 = 824,
    Snorlax6 = 825,
    Snorlax7 = 826,
    Snorlax8 = 827,
    Salamence5 = 828,
    Salamence6 = 829,
    Salamence7 = 830,
    Salamence8 = 831,
    Metagross5 = 832,
    Metagross6 = 833,
    Metagross7 = 834,
    Metagross8 = 835,
    Regirock5 = 836,
    Regirock6 = 837,
    Regice5 = 838,
    Regice6 = 839,
    Registeel5 = 840,
    Registeel6 = 841,
    Latias5 = 842,
    Latias6 = 843,
    Latias7 = 844,
    Latias8 = 845,
    Latios5 = 846,
    Latios6 = 847,
    Latios7 = 848,
    Latios8 = 849,
    MonsHighTier = 849, // marker
    Dragonite1 = 850,
    Dragonite2 = 851,
    Dragonite3 = 852,
    Dragonite4 = 853,
    Dragonite5 = 854,
    Dragonite6 = 855,
    Dragonite7 = 856,
    Dragonite8 = 857,
    Dragonite9 = 858,
    Dragonite10 = 859,
    Tyranitar1 = 860,
    Tyranitar2 = 861,
    Tyranitar3 = 862,
    Tyranitar4 = 863,
    Tyranitar5 = 864,
    Tyranitar6 = 865,
    Tyranitar7 = 866,
    Tyranitar8 = 867,
    Tyranitar9 = 868,
    Tyranitar10 = 869,
    Articuno5 = 870,
    Articuno6 = 871,
    Zapdos5 = 872,
    Zapdos6 = 873,
    Moltres5 = 874,
    Moltres6 = 875,
    Raikou5 = 876,
    Raikou6 = 877,
    Entei5 = 878,
    Entei6 = 879,
    Suicune5 = 880,
    Suicune6 = 881,
    NumFrontierMons = 882
}

public static class FrontierMons
{
    public static string[] FrontierMonNames =
    {
        "Sunkern",
        "Azurill",
        "Caterpie",
        "Weedle",
        "Wurmple",
        "Ralts",
        "Magikarp",
        "Feebas",
        "Metapod",
        "Kakuna",
        "Pichu",
        "Silcoon",
        "Cascoon",
        "Igglybuff",
        "Wooper",
        "Tyrogue",
        "Sentret",
        "Cleffa",
        "Seedot",
        "Lotad",
        "Poochyena",
        "Shedinja",
        "Makuhita",
        "Whismur",
        "Zigzagoon",
        "Zubat",
        "Togepi",
        "Spinarak",
        "Marill",
        "Hoppip",
        "Slugma",
        "Swinub",
        "Smeargle",
        "Pidgey",
        "Rattata",
        "Wynaut",
        "Skitty",
        "Spearow",
        "Hoothoot",
        "Diglett",
        "Ledyba",
        "Nincada",
        "Surskit",
        "Jigglypuff",
        "Taillow",
        "Wingull",
        "NidoranM",
        "NidoranF",
        "Kirlia",
        "Mareep",
        "Meditite",
        "Slakoth",
        "Paras",
        "Ekans",
        "Ditto",
        "Barboach",
        "Meowth",
        "Pineco",
        "Trapinch",
        "Spheal",
        "Horsea",
        "Shroomish",
        "Shuppet",
        "Duskull",
        "Electrike",
        "Vulpix",
        "Pikachu",
        "Sandshrew",
        "Poliwag",
        "Bellsprout",
        "Geodude",
        "Dratini",
        "Snubbull",
        "Remoraid",
        "Larvitar",
        "Baltoy",
        "Snorunt",
        "Bagon",
        "Beldum",
        "Gulpin",
        "Venonat",
        "Mankey",
        "Machop",
        "Shellder",
        "Smoochum",
        "Numel",
        "Carvanha",
        "Corphish",
        "Charmander",
        "Cyndaquil",
        "Abra",
        "Doduo",
        "Gastly",
        "Swablu",
        "Treecko",
        "Torchic",
        "Mudkip",
        "Squirtle",
        "Totodile",
        "Slowpoke",
        "Bulbasaur",
        "Chikorita",
        "Oddish",
        "Psyduck",
        "Cubone",
        "Goldeen",
        "Natu",
        "Clefairy",
        "Magnemite",
        "Seel",
        "Grimer",
        "Krabby",
        "Exeggcute",
        "Eevee",
        "Drowzee",
        "Voltorb",
        "Chinchou",
        "Teddiursa",
        "Delibird",
        "Houndour",
        "Phanpy",
        "Spoink",
        "Aron",
        "Luvdisc",
        "Tentacool",
        "Cacnea",
        "Unown",
        "Koffing",
        "Staryu",
        "Skiploom",
        "Nuzleaf",
        "Lombre",
        "Vibrava",
        "Rhyhorn",
        "Clamperl",
        "Pidgeotto",
        "Growlithe",
        "Farfetchd",
        "Omanyte",
        "Kabuto",
        "Lileep",
        "Anorith",
        "Aipom",
        "Elekid",
        "Loudred",
        "Spinda",
        "Nidorina",
        "Nidorino",
        "Flaaffy",
        "Magby",
        "Nosepass",
        "Corsola",
        "Mawile",
        "Butterfree",
        "Beedrill",
        "Poliwhirl",
        "Onix",
        "Beautifly",
        "Dustox",
        "Ledian",
        "Ariados",
        "Yanma",
        "Delcatty-1",
        "Sableye-1",
        "Lickitung-1",
        "Weepinbell-1",
        "Graveler-1",
        "Gloom-1",
        "Porygon-1",
        "Kadabra-1",
        "Wailmer-1",
        "Roselia-1",
        "Volbeat-1",
        "Illumise-1",
        "Ivysaur-1",
        "Charmeleon-1",
        "Wartortle-1",
        "Parasect-1",
        "Machoke-1",
        "Haunter-1",
        "Bayleef-1",
        "Quilava-1",
        "Croconaw-1",
        "Togetic-1",
        "Murkrow-1",
        "Wobbuffet-1",
        "Plusle-1",
        "Minun-1",
        "Grovyle-1",
        "Combusken-1",
        "Marshtomp-1",
        "Ponyta-1",
        "Azumarill-1",
        "Sudowoodo-1",
        "Magcargo-1",
        "Pupitar-1",
        "Sealeo-1",
        "Raticate-1",
        "Masquerain-1",
        "Furret-1",
        "Dunsparce-1",
        "Dragonair-1",
        "Mightyena-1",
        "Linoone-1",
        "Castform-1",
        "Shelgon-1",
        "Metang-1",
        "Wigglytuff-1",
        "Sunflora-1",
        "Chimecho-1",
        "Gligar-1",
        "Qwilfish-1",
        "Sneasel-1",
        "Pelipper-1",
        "Swellow-1",
        "Lairon-1",
        "Tangela-1",
        "Arbok-1",
        "Persian-1",
        "Seadra-1",
        "Kecleon-1",
        "Vigoroth-1",
        "Lunatone-1",
        "Solrock-1",
        "Noctowl-1",
        "Sandslash-1",
        "Venomoth-1",
        "Chansey-1",
        "Seaking-1",
        "Jumpluff-1",
        "Piloswine-1",
        "Golbat-1",
        "Primeape-1",
        "Hitmonlee-1",
        "Hitmonchan-1",
        "Girafarig-1",
        "Hitmontop-1",
        "Banette-1",
        "Ninjask-1",
        "Seviper-1",
        "Zangoose-1",
        "Camerupt-1",
        "Sharpedo-1",
        "Tropius-1",
        "Magneton-1",
        "Mantine-1",
        "Stantler-1",
        "Absol-1",
        "Swalot-1",
        "Crawdaunt-1",
        "Pidgeot-1",
        "Grumpig-1",
        "Torkoal-1",
        "Kingler-1",
        "Cacturne-1",
        "Bellossom-1",
        "Octillery-1",
        "Huntail-1",
        "Gorebyss-1",
        "Relicanth-1",
        "Omastar-1",
        "Kabutops-1",
        "Poliwrath-1",
        "Scyther-1",
        "Pinsir-1",
        "Politoed-1",
        "Cloyster-1",
        "Delcatty-2",
        "Sableye-2",
        "Lickitung-2",
        "Weepinbell-2",
        "Graveler-2",
        "Gloom-2",
        "Porygon-2",
        "Kadabra-2",
        "Wailmer-2",
        "Roselia-2",
        "Volbeat-2",
        "Illumise-2",
        "Ivysaur-2",
        "Charmeleon-2",
        "Wartortle-2",
        "Parasect-2",
        "Machoke-2",
        "Haunter-2",
        "Bayleef-2",
        "Quilava-2",
        "Croconaw-2",
        "Togetic-2",
        "Murkrow-2",
        "Wobbuffet-2",
        "Plusle-2",
        "Minun-2",
        "Grovyle-2",
        "Combusken-2",
        "Marshtomp-2",
        "Ponyta-2",
        "Azumarill-2",
        "Sudowoodo-2",
        "Magcargo-2",
        "Pupitar-2",
        "Sealeo-2",
        "Raticate-2",
        "Masquerain-2",
        "Furret-2",
        "Dunsparce-2",
        "Dragonair-2",
        "Mightyena-2",
        "Linoone-2",
        "Castform-2",
        "Shelgon-2",
        "Metang-2",
        "Wigglytuff-2",
        "Sunflora-2",
        "Chimecho-2",
        "Gligar-2",
        "Qwilfish-2",
        "Sneasel-2",
        "Pelipper-2",
        "Swellow-2",
        "Lairon-2",
        "Tangela-2",
        "Arbok-2",
        "Persian-2",
        "Seadra-2",
        "Kecleon-2",
        "Vigoroth-2",
        "Lunatone-2",
        "Solrock-2",
        "Noctowl-2",
        "Sandslash-2",
        "Venomoth-2",
        "Chansey-2",
        "Seaking-2",
        "Jumpluff-2",
        "Piloswine-2",
        "Golbat-2",
        "Primeape-2",
        "Hitmonlee-2",
        "Hitmonchan-2",
        "Girafarig-2",
        "Hitmontop-2",
        "Banette-2",
        "Ninjask-2",
        "Seviper-2",
        "Zangoose-2",
        "Camerupt-2",
        "Sharpedo-2",
        "Tropius-2",
        "Magneton-2",
        "Mantine-2",
        "Stantler-2",
        "Absol-2",
        "Swalot-2",
        "Crawdaunt-2",
        "Pidgeot-2",
        "Grumpig-2",
        "Torkoal-2",
        "Kingler-2",
        "Cacturne-2",
        "Bellossom-2",
        "Octillery-2",
        "Huntail-2",
        "Gorebyss-2",
        "Relicanth-2",
        "Omastar-2",
        "Kabutops-2",
        "Poliwrath-2",
        "Scyther-2",
        "Pinsir-2",
        "Politoed-2",
        "Cloyster-2",
        "Dugtrio-1",
        "Medicham-1",
        "Misdreavus-1",
        "Fearow-1",
        "Granbull-1",
        "Jynx-1",
        "Dusclops-1",
        "Dodrio-1",
        "MrMime-1",
        "Lanturn-1",
        "Breloom-1",
        "Forretress-1",
        "Whiscash-1",
        "Xatu-1",
        "Skarmory-1",
        "Marowak-1",
        "Quagsire-1",
        "Clefable-1",
        "Hariyama-1",
        "Raichu-1",
        "Dewgong-1",
        "Manectric-1",
        "Vileplume-1",
        "Victreebel-1",
        "Electrode-1",
        "Exploud-1",
        "Shiftry-1",
        "Glalie-1",
        "Ludicolo-1",
        "Hypno-1",
        "Golem-1",
        "Rhydon-1",
        "Alakazam-1",
        "Weezing-1",
        "Kangaskhan-1",
        "Electabuzz-1",
        "Tauros-1",
        "Slowbro-1",
        "Slowking-1",
        "Miltank-1",
        "Altaria-1",
        "Nidoqueen-1",
        "Nidoking-1",
        "Magmar-1",
        "Cradily-1",
        "Armaldo-1",
        "Golduck-1",
        "Rapidash-1",
        "Muk-1",
        "Gengar-1",
        "Ampharos-1",
        "Scizor-1",
        "Heracross-1",
        "Ursaring-1",
        "Houndoom-1",
        "Donphan-1",
        "Claydol-1",
        "Wailord-1",
        "Ninetales-1",
        "Machamp-1",
        "Shuckle-1",
        "Steelix-1",
        "Tentacruel-1",
        "Aerodactyl-1",
        "Porygon-2-1",
        "Gardevoir-1",
        "Exeggutor-1",
        "Starmie-1",
        "Flygon-1",
        "Venusaur-1",
        "Vaporeon-1",
        "Jolteon-1",
        "Flareon-1",
        "Meganium-1",
        "Espeon-1",
        "Umbreon-1",
        "Blastoise-1",
        "Feraligatr-1",
        "Aggron-1",
        "Blaziken-1",
        "Walrein-1",
        "Sceptile-1",
        "Charizard-1",
        "Typhlosion-1",
        "Lapras-1",
        "Crobat-1",
        "Swampert-1",
        "Gyarados-1",
        "Snorlax-1",
        "Kingdra-1",
        "Blissey-1",
        "Milotic-1",
        "Arcanine-1",
        "Salamence-1",
        "Metagross-1",
        "Slaking-1",
        "Dugtrio-2",
        "Medicham-2",
        "Marowak-2",
        "Quagsire-2",
        "Misdreavus-2",
        "Fearow-2",
        "Granbull-2",
        "Jynx-2",
        "Dusclops-2",
        "Dodrio-2",
        "MrMime-2",
        "Lanturn-2",
        "Breloom-2",
        "Forretress-2",
        "Skarmory-2",
        "Whiscash-2",
        "Xatu-2",
        "Clefable-2",
        "Hariyama-2",
        "Raichu-2",
        "Dewgong-2",
        "Manectric-2",
        "Vileplume-2",
        "Victreebel-2",
        "Electrode-2",
        "Exploud-2",
        "Shiftry-2",
        "Glalie-2",
        "Ludicolo-2",
        "Hypno-2",
        "Golem-2",
        "Rhydon-2",
        "Alakazam-2",
        "Weezing-2",
        "Kangaskhan-2",
        "Electabuzz-2",
        "Tauros-2",
        "Slowbro-2",
        "Slowking-2",
        "Miltank-2",
        "Altaria-2",
        "Nidoqueen-2",
        "Nidoking-2",
        "Magmar-2",
        "Cradily-2",
        "Armaldo-2",
        "Golduck-2",
        "Rapidash-2",
        "Muk-2",
        "Gengar-2",
        "Ampharos-2",
        "Scizor-2",
        "Heracross-2",
        "Ursaring-2",
        "Houndoom-2",
        "Donphan-2",
        "Claydol-2",
        "Wailord-2",
        "Ninetales-2",
        "Machamp-2",
        "Shuckle-2",
        "Steelix-2",
        "Tentacruel-2",
        "Aerodactyl-2",
        "Porygon-2-2",
        "Gardevoir-2",
        "Exeggutor-2",
        "Starmie-2",
        "Flygon-2",
        "Venusaur-2",
        "Vaporeon-2",
        "Jolteon-2",
        "Flareon-2",
        "Meganium-2",
        "Espeon-2",
        "Umbreon-2",
        "Blastoise-2",
        "Feraligatr-2",
        "Aggron-2",
        "Blaziken-2",
        "Walrein-2",
        "Sceptile-2",
        "Charizard-2",
        "Typhlosion-2",
        "Lapras-2",
        "Crobat-2",
        "Swampert-2",
        "Gyarados-2",
        "Snorlax-2",
        "Kingdra-2",
        "Blissey-2",
        "Milotic-2",
        "Arcanine-2",
        "Salamence-2",
        "Metagross-2",
        "Slaking-2",
        "Dugtrio-3",
        "Medicham-3",
        "Misdreavus-3",
        "Fearow-3",
        "Granbull-3",
        "Jynx-3",
        "Dusclops-3",
        "Dodrio-3",
        "MrMime-3",
        "Lanturn-3",
        "Breloom-3",
        "Forretress-3",
        "Whiscash-3",
        "Xatu-3",
        "Skarmory-3",
        "Marowak-3",
        "Quagsire-3",
        "Clefable-3",
        "Hariyama-3",
        "Raichu-3",
        "Dewgong-3",
        "Manectric-3",
        "Vileplume-3",
        "Victreebel-3",
        "Electrode-3",
        "Exploud-3",
        "Shiftry-3",
        "Glalie-3",
        "Ludicolo-3",
        "Hypno-3",
        "Golem-3",
        "Rhydon-3",
        "Alakazam-3",
        "Weezing-3",
        "Kangaskhan-3",
        "Electabuzz-3",
        "Tauros-3",
        "Slowbro-3",
        "Slowking-3",
        "Miltank-3",
        "Altaria-3",
        "Nidoqueen-3",
        "Nidoking-3",
        "Magmar-3",
        "Cradily-3",
        "Armaldo-3",
        "Golduck-3",
        "Rapidash-3",
        "Muk-3",
        "Gengar-3",
        "Ampharos-3",
        "Scizor-3",
        "Heracross-3",
        "Ursaring-3",
        "Houndoom-3",
        "Donphan-3",
        "Claydol-3",
        "Wailord-3",
        "Ninetales-3",
        "Machamp-3",
        "Shuckle-3",
        "Steelix-3",
        "Tentacruel-3",
        "Aerodactyl-3",
        "Porygon-2-3",
        "Gardevoir-3",
        "Exeggutor-3",
        "Starmie-3",
        "Flygon-3",
        "Venusaur-3",
        "Vaporeon-3",
        "Jolteon-3",
        "Flareon-3",
        "Meganium-3",
        "Espeon-3",
        "Umbreon-3",
        "Blastoise-3",
        "Feraligatr-3",
        "Aggron-3",
        "Blaziken-3",
        "Walrein-3",
        "Sceptile-3",
        "Charizard-3",
        "Typhlosion-3",
        "Lapras-3",
        "Crobat-3",
        "Swampert-3",
        "Gyarados-3",
        "Snorlax-3",
        "Kingdra-3",
        "Blissey-3",
        "Milotic-3",
        "Arcanine-3",
        "Salamence-3",
        "Metagross-3",
        "Slaking-3",
        "Dugtrio-4",
        "Medicham-4",
        "Misdreavus-4",
        "Fearow-4",
        "Granbull-4",
        "Jynx-4",
        "Dusclops-4",
        "Dodrio-4",
        "MrMime-4",
        "Lanturn-4",
        "Breloom-4",
        "Forretress-4",
        "Whiscash-4",
        "Xatu-4",
        "Skarmory-4",
        "Marowak-4",
        "Quagsire-4",
        "Clefable-4",
        "Hariyama-4",
        "Raichu-4",
        "Dewgong-4",
        "Manectric-4",
        "Vileplume-4",
        "Victreebel-4",
        "Electrode-4",
        "Exploud-4",
        "Shiftry-4",
        "Glalie-4",
        "Ludicolo-4",
        "Hypno-4",
        "Golem-4",
        "Rhydon-4",
        "Alakazam-4",
        "Weezing-4",
        "Kangaskhan-4",
        "Electabuzz-4",
        "Tauros-4",
        "Slowbro-4",
        "Slowking-4",
        "Miltank-4",
        "Altaria-4",
        "Nidoqueen-4",
        "Nidoking-4",
        "Magmar-4",
        "Cradily-4",
        "Armaldo-4",
        "Golduck-4",
        "Rapidash-4",
        "Muk-4",
        "Gengar-4",
        "Ampharos-4",
        "Scizor-4",
        "Heracross-4",
        "Ursaring-4",
        "Houndoom-4",
        "Donphan-4",
        "Claydol-4",
        "Wailord-4",
        "Ninetales-4",
        "Machamp-4",
        "Shuckle-4",
        "Steelix-4",
        "Tentacruel-4",
        "Aerodactyl-4",
        "Porygon-2-4",
        "Gardevoir-4",
        "Exeggutor-4",
        "Starmie-4",
        "Flygon-4",
        "Venusaur-4",
        "Vaporeon-4",
        "Jolteon-4",
        "Flareon-4",
        "Meganium-4",
        "Espeon-4",
        "Umbreon-4",
        "Blastoise-4",
        "Feraligatr-4",
        "Aggron-4",
        "Blaziken-4",
        "Walrein-4",
        "Sceptile-4",
        "Charizard-4",
        "Typhlosion-4",
        "Lapras-4",
        "Crobat-4",
        "Swampert-4",
        "Gyarados-4",
        "Snorlax-4",
        "Kingdra-4",
        "Blissey-4",
        "Milotic-4",
        "Arcanine-4",
        "Salamence-4",
        "Metagross-4",
        "Slaking-4",
        "Articuno-1",
        "Zapdos-1",
        "Moltres-1",
        "Raikou-1",
        "Entei-1",
        "Suicune-1",
        "Regirock-1",
        "Regice-1",
        "Registeel-1",
        "Latias-1",
        "Latios-1",
        "Articuno-2",
        "Zapdos-2",
        "Moltres-2",
        "Raikou-2",
        "Entei-2",
        "Suicune-2",
        "Regirock-2",
        "Regice-2",
        "Registeel-2",
        "Latias-2",
        "Latios-2",
        "Articuno-3",
        "Zapdos-3",
        "Moltres-3",
        "Raikou-3",
        "Entei-3",
        "Suicune-3",
        "Regirock-3",
        "Regice-3",
        "Registeel-3",
        "Latias-3",
        "Latios-3",
        "Articuno-4",
        "Zapdos-4",
        "Moltres-4",
        "Raikou-4",
        "Entei-4",
        "Suicune-4",
        "Regirock-4",
        "Regice-4",
        "Registeel-4",
        "Latias-4",
        "Latios-4",
        "Gengar-5",
        "Gengar-6",
        "Gengar-7",
        "Gengar-8",
        "Ursaring-5",
        "Ursaring-6",
        "Ursaring-7",
        "Ursaring-8",
        "Machamp-5",
        "Machamp-6",
        "Machamp-7",
        "Machamp-8",
        "Gardevoir-5",
        "Gardevoir-6",
        "Gardevoir-7",
        "Gardevoir-8",
        "Starmie-5",
        "Starmie-6",
        "Starmie-7",
        "Starmie-8",
        "Lapras-5",
        "Lapras-6",
        "Lapras-7",
        "Lapras-8",
        "Snorlax-5",
        "Snorlax-6",
        "Snorlax-7",
        "Snorlax-8",
        "Salamence-5",
        "Salamence-6",
        "Salamence-7",
        "Salamence-8",
        "Metagross-5",
        "Metagross-6",
        "Metagross-7",
        "Metagross-8",
        "Regirock-5",
        "Regirock-6",
        "Regice-5",
        "Regice-6",
        "Registeel-5",
        "Registeel-6",
        "Latias-5",
        "Latias-6",
        "Latias-7",
        "Latias-8",
        "Latios-5",
        "Latios-6",
        "Latios-7",
        "Latios-8",
        "Dragonite-1",
        "Dragonite-2",
        "Dragonite-3",
        "Dragonite-4",
        "Dragonite-5",
        "Dragonite-6",
        "Dragonite-7",
        "Dragonite-8",
        "Dragonite-9",
        "Dragonite-1-0",
        "Tyranitar-1",
        "Tyranitar-2",
        "Tyranitar-3",
        "Tyranitar-4",
        "Tyranitar-5",
        "Tyranitar-6",
        "Tyranitar-7",
        "Tyranitar-8",
        "Tyranitar-9",
        "Tyranitar-1-0",
        "Articuno-5",
        "Articuno-6",
        "Zapdos-5",
        "Zapdos-6",
        "Moltres-5",
        "Moltres-6",
        "Raikou-5",
        "Raikou-6",
        "Entei-5",
        "Entei-6",
        "Suicune-5",
        "Suicune-6",
    };

    public static Nature[] FrontierMonNatures =
    {
        Nature.Relaxed,
        Nature.Rash,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Docile,
        Nature.Hardy,
        Nature.Lonely,
        Nature.Bashful,
        Nature.Bashful,
        Nature.Rash,
        Nature.Bashful,
        Nature.Bashful,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Serious,
        Nature.Docile,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Naive,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Timid,
        Nature.Sassy,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Gentle,
        Nature.Lax,
        Nature.Sassy,
        Nature.Gentle,
        Nature.Hardy,
        Nature.Lonely,
        Nature.Docile,
        Nature.Jolly,
        Nature.Docile,
        Nature.Docile,
        Nature.Quirky,
        Nature.Naive,
        Nature.Bashful,
        Nature.Calm,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Gentle,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Naughty,
        Nature.Quirky,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Hardy,
        Nature.Bashful,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Serious,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Rash,
        Nature.Quirky,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Lax,
        Nature.Brave,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Naughty,
        Nature.Naughty,
        Nature.Brave,
        Nature.Naughty,
        Nature.Hardy,
        Nature.Serious,
        Nature.Relaxed,
        Nature.Naughty,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Hardy,
        Nature.Quiet,
        Nature.Brave,
        Nature.Docile,
        Nature.Docile,
        Nature.Lonely,
        Nature.Lonely,
        Nature.Lonely,
        Nature.Lonely,
        Nature.Lonely,
        Nature.Lonely,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Brave,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Hasty,
        Nature.Hardy,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Lonely,
        Nature.Gentle,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Naughty,
        Nature.Docile,
        Nature.Quirky,
        Nature.Docile,
        Nature.Hardy,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Docile,
        Nature.Naughty,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Docile,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Docile,
        Nature.Quirky,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Docile,
        Nature.Hardy,
        Nature.Relaxed,
        Nature.Naive,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Mild,
        Nature.Docile,
        Nature.Sassy,
        Nature.Impish,
        Nature.Docile,
        Nature.Quirky,
        Nature.Naughty,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Docile,
        Nature.Docile,
        Nature.Bashful,
        Nature.Serious,
        Nature.Relaxed,
        Nature.Lonely,
        Nature.Lonely,
        Nature.Quirky,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Relaxed,
        Nature.Impish,
        Nature.Docile,
        Nature.Docile,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Gentle,
        Nature.Naughty,
        Nature.Docile,
        Nature.Rash,
        Nature.Adamant,
        Nature.Rash,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Careful,
        Nature.Docile,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Docile,
        Nature.Hardy,
        Nature.Gentle,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Naive,
        Nature.Relaxed,
        Nature.Serious,
        Nature.Docile,
        Nature.Docile,
        Nature.Timid,
        Nature.Adamant,
        Nature.Hasty,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Sassy,
        Nature.Hasty,
        Nature.Impish,
        Nature.Relaxed,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Sassy,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Sassy,
        Nature.Naive,
        Nature.Lonely,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Relaxed,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Docile,
        Nature.Quirky,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Sassy,
        Nature.Mild,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Lonely,
        Nature.Docile,
        Nature.Gentle,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Hardy,
        Nature.Hasty,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Quiet,
        Nature.Brave,
        Nature.Sassy,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Naughty,
        Nature.Relaxed,
        Nature.Sassy,
        Nature.Modest,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Quiet,
        Nature.Modest,
        Nature.Docile,
        Nature.Docile,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Docile,
        Nature.Calm,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Docile,
        Nature.Docile,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Quirky,
        Nature.Careful,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Jolly,
        Nature.Modest,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Docile,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Jolly,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Sassy,
        Nature.Calm,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Docile,
        Nature.Docile,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Docile,
        Nature.Relaxed,
        Nature.Impish,
        Nature.Bold,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Sassy,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Modest,
        Nature.Quirky,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Sassy,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Jolly,
        Nature.Modest,
        Nature.Careful,
        Nature.Adamant,
        Nature.Docile,
        Nature.Impish,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Impish,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Quiet,
        Nature.Jolly,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Brave,
        Nature.Adamant,
        Nature.Modest,
        Nature.Quiet,
        Nature.Modest,
        Nature.Impish,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Impish,
        Nature.Quiet,
        Nature.Modest,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Careful,
        Nature.Docile,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Relaxed,
        Nature.Relaxed,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Timid,
        Nature.Relaxed,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Docile,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Sassy,
        Nature.Modest,
        Nature.Adamant,
        Nature.Brave,
        Nature.Adamant,
        Nature.Impish,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Timid,
        Nature.Quiet,
        Nature.Modest,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Bold,
        Nature.Modest,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Docile,
        Nature.Quiet,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Bold,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Careful,
        Nature.Adamant,
        Nature.Modest,
        Nature.Bold,
        Nature.Modest,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Sassy,
        Nature.Bold,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Impish,
        Nature.Impish,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Adamant,
        Nature.Careful,
        Nature.Hardy,
        Nature.Impish,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Docile,
        Nature.Modest,
        Nature.Bold,
        Nature.Serious,
        Nature.Modest,
        Nature.Quirky,
        Nature.Impish,
        Nature.Quirky,
        Nature.Modest,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Careful,
        Nature.Bold,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Docile,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Jolly,
        Nature.Adamant,
        Nature.Modest,
        Nature.Jolly,
        Nature.Calm,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Careful,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Hardy,
        Nature.Modest,
        Nature.Modest,
        Nature.Bold,
        Nature.Docile,
        Nature.Hardy,
        Nature.Relaxed,
        Nature.Calm,
        Nature.Docile,
        Nature.Adamant,
        Nature.Brave,
        Nature.Sassy,
        Nature.Adamant,
        Nature.Docile,
        Nature.Quirky,
        Nature.Modest,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Timid,
        Nature.Calm,
        Nature.Docile,
        Nature.Modest,
        Nature.Adamant,
        Nature.Modest,
        Nature.Bold,
        Nature.Modest,
        Nature.Docile,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Bold,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Jolly,
        Nature.Careful,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Docile,
        Nature.Bold,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Quirky,
        Nature.Naughty,
        Nature.Modest,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Bold,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Quirky,
        Nature.Jolly,
        Nature.Quirky,
        Nature.Docile,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Impish,
        Nature.Modest,
        Nature.Adamant,
        Nature.Docile,
        Nature.Modest,
        Nature.Quiet,
        Nature.Modest,
        Nature.Hardy,
        Nature.Careful,
        Nature.Adamant,
        Nature.Modest,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Careful,
        Nature.Adamant,
        Nature.Modest,
        Nature.Hardy,
        Nature.Modest,
        Nature.Modest,
        Nature.Hardy,
        Nature.Modest,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Calm,
        Nature.Bold,
        Nature.Jolly,
        Nature.Jolly,
        Nature.Modest,
        Nature.Bold,
        Nature.Docile,
        Nature.Hardy,
        Nature.Modest,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Docile,
        Nature.Modest,
        Nature.Adamant,
        Nature.Docile,
        Nature.Adamant,
        Nature.Brave,
        Nature.Quirky,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Bold,
        Nature.Bold,
        Nature.Modest,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Timid,
        Nature.Hardy,
        Nature.Brave,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Docile,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Sassy,
        Nature.Docile,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Modest,
        Nature.Quiet,
        Nature.Quirky,
        Nature.Naughty,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Bold,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Sassy,
        Nature.Modest,
        Nature.Adamant,
        Nature.Docile,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Bold,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Brave,
        Nature.Modest,
        Nature.Modest,
        Nature.Careful,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Careful,
        Nature.Adamant,
        Nature.Quirky,
        Nature.Hardy,
        Nature.Modest,
        Nature.Modest,
        Nature.Hardy,
        Nature.Modest,
        Nature.Hardy,
        Nature.Docile,
        Nature.Calm,
        Nature.Timid,
        Nature.Quiet,
        Nature.Hardy,
        Nature.Modest,
        Nature.Bold,
        Nature.Docile,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Quiet,
        Nature.Modest,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Modest,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Bold,
        Nature.Modest,
        Nature.Docile,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Modest,
        Nature.Modest,
        Nature.Docile,
        Nature.Docile,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Impish,
        Nature.Docile,
        Nature.Hardy,
        Nature.Modest,
        Nature.Modest,
        Nature.Calm,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Quiet,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Modest,
        Nature.Modest,
        Nature.Docile,
        Nature.Modest,
        Nature.Adamant,
        Nature.Quiet,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Quiet,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Careful,
        Nature.Bold,
        Nature.Impish,
        Nature.Docile,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Docile,
        Nature.Timid,
        Nature.Bold,
        Nature.Modest,
        Nature.Modest,
        Nature.Calm,
        Nature.Modest,
        Nature.Modest,
        Nature.Docile,
        Nature.Modest,
        Nature.Calm,
        Nature.Calm,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Modest,
        Nature.Modest,
        Nature.Jolly,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Brave,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Modest,
        Nature.Modest,
        Nature.Adamant,
        Nature.Docile,
        Nature.Modest,
        Nature.Docile,
        Nature.Adamant,
        Nature.Docile,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Docile,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
        Nature.Docile,
        Nature.Docile,
        Nature.Hardy,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Modest,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Adamant,
        Nature.Hardy,
        Nature.Adamant,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Docile,
        Nature.Modest,
        Nature.Modest,
        Nature.Docile,
        Nature.Modest,
        Nature.Modest,
        Nature.Modest,
    };
}
